# Generated by Django 5.1.2 on 2024-10-31 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jeudeplateau',
            name='createur',
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_retour',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 16, 16, 10, 298371, tzinfo=datetime.timezone.utc)),
        ),
    ]
